### ISSUE TITLE
A revised version of the Wavulike illustration with callouts added

### ISSUE THREAD

**Issue by heurihermilab** [Miff-Real/DanTModules-Manual#1]
![wavulike-rev](https://user-images.githubusercontent.com/26681465/101292924-52141700-37c7-11eb-80f9-98a446e7bbac.png)

**Comment by Miff-Real** [comment]
Nice, thanks for the input, i'll add this to the manual page

**Comment by Miff-Real** [comment]
Manual updated, thanks again.
