### ISSUE TITLE
Purfenator + PolySplice : Panel's colour can't be changed

### ISSUE THREAD

**Issue by Donmanouche** [Miff-Real/DanTModules-Manual#23]
Hi,

As written in the title, the panel's colour of the modules Purfenator and PolySplice (at least) cannot be changed in my VCV Rack. Changing the colour values in the menu have no effect on the modules 

I am running VCV Rack Pro 2.4.1 on Linux (Kubuntu 22.04). The issue was identified on the standalone version. I haven't tried in the VSTs (no reason it would be different).

**Comment by Miff-Real** [comment]
Can you post a video or screenshot to help diagnose the issue?

Do the menu controls interact correctly, what colour are the module panels?

Does Rack report a crash at all, is there any information in the `log.txt` file?

Does this happen for every patch, or only specific patches?

**Comment by Miff-Real** [comment]
I am on Windows 11 and unfortunately I am not able to test on Linux at this time.

If you replicate the same setup as me, and capture a screenshot, then we can compare.

This is a new patch, with all modules removed, and only PolySplice added, then I have set Red to full, and Green and Blue to zero:

![image](https://github.com/Miff-Real/DanTModules-Manual/assets/1334054/b51c3ddb-b06b-4a69-b601-d737018d4933)

**Comment by Donmanouche** [comment]
Here you go

![image](https://github.com/Miff-Real/DanTModules-Manual/assets/107601402/b1599f0d-6b61-4af8-b914-7b5682a53f57)

**Comment by Miff-Real** [comment]
The RGB values for the panel colour are stored at runtime in an `extern` variable, and then saved locally to a config file `DanTNuMetal.json`.

Can you please take a look in your Rack directory and see if this file exists, and if so what is the content?

It should look something like this:

```
{
  "userPortTypeColours": true,
  "userKnobColours": true,
  "userKnobDisplays": true,
  "userDisplaysLit": true,
  "userPanelLightText": false,
  "userPanelRValue": 255,
  "userPanelGValue": 0,
  "userPanelBValue": 0
}
```

If it does exist, could you try closing Rack, editing the RGB values and reopening Rack to see if the panel colour is affected?

**Comment by Miff-Real** [comment]
Oh, wait a second, I think I've just seen the issue.

You have the `Plugin Respects Dark Panels Setting` active, and you most likely have the Rack `View -> Use dark panels if available (experimental)` setting active too?

Deactivate the `Plugin Respects Dark Panels Setting` option and the panel colour should work...?

**Comment by Donmanouche** [comment]
That solved the issue! Thank you!

**Comment by Miff-Real** [comment]
👍
