### ISSUE TITLE
Purfenator feature request: Show VCV Rack's power rail inside the skiff.

### ISSUE THREAD

**Issue by cosmoproductions** [Miff-Real/DanTModules-Manual#25]
Hi Dan.
The title says it all.  I'm kinda missing the look of VCV's power rail inside the Purfenated case.  Empty areas in the case are left completely blank showing the flat color configured in the Inside colour parameter.  Considering how the layering is restricting what you can do with this module, here are a couple suggestion for your kind consideration.

1. Add alpha to Inside colour controls, to show through to whatever is back there: a background image if that's enabled, background colour/gradient if that's enabled (the power rail would be visible if the BG color alpha is less than max and image isn't enabled), or the normal rack BG with power rail.  Whatever is in the BG would be tinted with the Inside colour when alpha is transparent.
2. powerrails.png.  Include an option to turn on the power rail, like you're doing with the screw's rail.  Whatever is in the BG would show through the alpha of the png as it's doing with skiffrails.png.

My preference is for the first option.  It seems simpler and more flexible. I imagine the second option would require the skiff to be multiples of the tiled power rail image, which could result in unwanted empty spaces on the sides of the rack.  It would also inevitably lead to people asking for more control over the colors of the power rail image. ;)

Great work on this and all your modules.
Thanks much!
Gabe

**Comment by Miff-Real** [comment]
Option 1 sounds good, it is flexible and allows many different configurations, and it shouldn't be too difficult to add, I'll aim for that.

**Comment by Miff-Real** [comment]
![image](https://github.com/Miff-Real/DanTModules-Manual/assets/1334054/8e5cc74c-3a10-4488-ba1c-2bfbb0536ce0)

Well, it works for what you want as long as you don't use a background colour or gradient or a background image that's behind the skiff.

I guess having a zero alpha is sort of like the skiff having no rear wall, if you are happy with this then I am happy with it...

**Comment by Miff-Real** [comment]
The alpha for the skiff inside colour is included as part of the Beta 01 build

https://ko-fi.com/post/January-2024--Beta-01-P5P7TN2C8

**Comment by cosmoproductions** [comment]
Hi Dan. Sorry for the delay in responding.  Thanks for trying out the change. If the extra option doesn't cause any problems, I suppose someone might want to use it like this.  But now that I see it in the image you shared, it seems unlikely to be popular with most people to use it this way.  Having no solid color and no BG image around the outside of the skiff kind of defeats the purpose of using the module to create a skiff graphic at all.  Seeing the rails outside of the skiff breaks the skeumorphic sense of there being a skiff holding the contents of the rack.  
But if there is a color, gradient, or image on and the skiff bottom alpha is set to less than full opaque, seeing the color or image both outside and inside the skiff seems like less of a visual problem, because it stills retain the sense that there's no rack components (rails and power rails) outside the skiff, thus keeping the sense of skeumorphism.  But of course in that case, there's no rail imagery inside the skiff.
Here's another idea. What about a toggle option to turn off the BG image inside the rack (no alpha slider, just on or off)?  The power rails would show through only inside the rack.  A BG solid/gradient with reduced alpha could still be used.  The result would look like the attached.  This image is a mock up I made of two images: BG image on and off, gradient opacity the same in both.
![purf dream v01](https://github.com/Miff-Real/DanTModules-Manual/assets/82449559/9423fb28-470e-4703-aef5-bbeb83d4c10e)

Thanks again for your great work.  If this change can't make the cut, I can understand.  "Small" changes like this can lead to bloated software.  The module is already great as is. 
Happy patching (and coding).
Gabe

**Comment by Miff-Real** [comment]
I am going to leave the inside skiff alpha control now it is there, its not harming anything.

Unfortunately I think the only way this feature can work is by overlaying a new power image just inside the skiff areas, but this is not as simple as it sounds either given multi-skiff mode...    I need to think about it a bit more, I'll carry this feature over to next month and decide later.

The Rack version of NanoVG, as far as I can tell, doesn't have a way to "cut out" an area of a shape. So because the image is painted to the entire screen, there isn't an easy way to have it not show on the inside of the skiff. Potentially it could be drawn as 4 rects around the skiff leaving the inside clear, but again this is much more complicated, and then it would also need to track the position of the skiff and alter the rects size on the fly (or multiple skiffs 😵‍💫).

**Comment by cosmoproductions** [comment]
Cool, yeah that sounds like way more trouble than it's worth for something that might be an edge case. Most people will likely want a nice tightly packed skiff with no gaps when using this module.  Thinking about it like led to me the obvious solution that's no work for you: computerscare's Custom Blank! I exported the rail.svg as a high resolution .png and set the Custom Blank's image scale setting to Fit Height.  Voila!

![DanT with computerscare blank rail image](https://github.com/Miff-Real/DanTModules-Manual/assets/82449559/9e0dd408-c641-4a37-a5ab-57af52a95a18)

In this image you can see I have Bernoulli Gates bg turned off in the svg so it appears transparent, showing through to the BG image same as Moar Cowbell.

**Comment by cosmoproductions** [comment]
From there it's a short leap to manually creating whatever whacky customizations I want for the inner power rail image.

![DanT with custom rail image](https://github.com/Miff-Real/DanTModules-Manual/assets/82449559/912e791a-07f8-487d-a9fb-ef752c247d39)

**Comment by Miff-Real** [comment]
Huhhh... interesting. Can you just check something for me to sate my curiosity?

It sounds like you had Purfenator in the patch already, and then you added the Computerscare blank.

Can you build a patch the opposite way (ie swap the order in which you add the modules to the patch) and let me know if there is any difference?

**Comment by cosmoproductions** [comment]
Correct, for those examples I had Purfenator in the patch and added Custom Blank.  Adding Custom Blank first and Purfenator second works fine, didn't cause any unusual behavior.  The following I added custom blank and set the image, purfenator and set the settings, then more custom blanks, just to be sure.  Everything seems to be working fine.

Purf off  (it's easier to see what I have loaded into the Custom Blanks):
![image](https://github.com/Miff-Real/DanTModules-Manual/assets/82449559/63f437af-fa8e-4580-9705-cbbf7c8279b7)

Same patch with Purf on:
![image](https://github.com/Miff-Real/DanTModules-Manual/assets/82449559/056639b9-5821-4b06-9688-f2e56170b628)

**Comment by Miff-Real** [comment]
Ah, sorry, I got confused, I was thinking of the Questionable Modules Greenscreen. That would either show above or below Purfenator depending on which was added first...

OK all good! Would you consider creating a small tutorial for customising the inside of the skiff (for either the VCV Community or the discussion board here)? I think other users would find it useful.

**Comment by Miff-Real** [comment]
Going to close this now, the skiff inside colour was added to the plugin v2.4.37 and pushed to the [VCV Rack library](https://library.vcvrack.com/DanTModules) on January 27th 2024. Please do open a new issue if you have additional requests or ideas for the skiff inside, thanks.

**Comment by cosmoproductions** [comment]
Great.  I'll see about putting together a simple tutorial on doing what I did.  You can probably understand, writing tutorials has a hard time making it to the top of the to-do list.  ;)   Thanks again!

**Comment by Miff-Real** [comment]
Of course, no pressure 👍
