### ISSUE TITLE
How to install DanT plugins in Rack2 ?

### ISSUE THREAD

**Issue by zebulon-1st** [Miff-Real/DanTModules-Manual#4]
System : Debian GNU/Linux 11 (bullseye)
$ uname -a : Linux debian-1 5.10.0-14-amd64 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

Hello,
Even by adding the all plugins from Rack Library web page and updating plugins from Rack Library menu entry "DanT Modules 2.3.3", none of the plugins wants to be installed.
Since they are not open-source and not compilable, how to get them ?

Regards.

**Comment by Miff-Real** [comment]
Hi, sorry you are having issues. Unfortunately, this is not an issue with my plugin. To get my plugin in Rack2 you simply need to subscribe to it from the VCV Library https://library.vcvrack.com/DanTModules

Make sure you are logged in with the same account on the library website and within the Rack application. When you run the app the `Library` menu should update and show any plugins/modules that have an update pending, once you restart the app the new modules should show in the browser.

If this normal process does not work, you will need to get help from either VCV support or the VCV community https://community.vcvrack.com/
